package:
  name: bw_calc-dev
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  script_env:
   - VERSION
   - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - pypardiso
    - stats_arrays

test:
  imports:
    - bw_calc

about:
  home: "https://github.com/brightway-lca/bw_calc"
  license: BSD License
  summary: 'Matrix calculations for Brightway framework'
license_family: BSD
